### ISSUE TITLE
Ads blocked by the AdBlock extension are also targeted by the program

### ISSUE THREAD

**Issue by varung97** [kabir-plod/spoiler-blocker#5]
For example, in the image below, AdBlock removed an ad between the 2 posts, but an overlay was placed on top of it:<br>
<img width="592" alt="screen shot 2016-12-07 at 2 28 23 pm" src="https://cloud.githubusercontent.com/assets/15965023/20957294/e2509d92-bc89-11e6-8837-f5a12dc5dcd0.png">

**Comment by kabirgh** [comment]
Looks like I might have accidentally remove the code that fixed this in the 0.1.0 release: https://github.com/kabir-plod/spoiler-blocker/blob/f9ca959877321a5b787e571dcb5424f0f2df2bf4/chrome/twitter.js#L98-L100

**Comment by kabirgh** [comment]
Please check if the issue is fixed by https://github.com/kabir-plod/spoiler-blocker/pull/10

**Comment by varung97** [comment]
Fixed
