### ISSUE TITLE
Overlay covers lines separating posts in Twitter

### ISSUE THREAD

**Issue by varung97** [kabir-plod/spoiler-blocker#6]
It looks like this:<br>
<img width="591" alt="screen shot 2016-12-07 at 2 35 49 pm" src="https://cloud.githubusercontent.com/assets/15965023/20957394/80f6c318-bc8a-11e6-9416-49a219f6d647.png">
Far as I can tell this is not showing up on Facebook, where posts are separated by a wider line.<br>
Possible fix is to reduce the percentage height of the overlay, but this may cause it to shorten too much on FB. Alternatively, the height of the overlay could differ for FB and Twitter...

**Comment by kabirgh** [comment]
Could pass the line heights as paramters in the fbConfig and twConfig objects - height of the overlays should differ for Facebook and Twitter.

**Comment by varung97** [comment]
Sure I'll do that
