### ISSUE TITLE
Case-insensitive Titles

### ISSUE THREAD

**Issue by varung97** [kabir-plod/spoiler-blocker#9]
I noticed the list titles are case-insensitive, in the sense that if I create a list with the title `asf`, I cannot create another with title `ASF`.
Thinking about whether we should treat them in this way, though it does seem unlikely anyway that the user would want to create two lists with the same name but different cases.

**Comment by kabirgh** [comment]
This is intentional behaviour. I'd think that have two lists with the same title is an oversight rather than a purposeful action.

**Comment by varung97** [comment]
Makes sense 👍
